
plugins {
    id 'java'
    id 'application'
}
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
repositories {
    repositories {
        mavenCentral()
    }
}

ext {
    jupiterVersion = '5.7.0'
}

dependencies {
    implementation 'net.dv8tion:JDA:5.0.0-beta.24'
    implementation 'ch.qos.logback:logback-classic:1.5.6'
    implementation 'net.aksingh:owm-japis:2.5.3.0'
    implementation 'com.google.code.gson:gson:2.8.5'
    testImplementation 'org.mockito:mockito-core:3.4.0'
    implementation 'org.springframework.boot:spring-boot-starter-webflux:2.4.1'
    testImplementation "org.junit.jupiter:junit-jupiter:${jupiterVersion}"
    testImplementation "org.junit.jupiter:junit-jupiter-migrationsupport:${jupiterVersion}"
}

group = 'org.jointheleague'
version = '2.0'
description = 'discordbot'
sourceCompatibility = '1.8'

run {
  environment "CHANNEL_NAME", "bot-mode"
  
  environment "DISCORD_TOKEN", "MTMzMTQ0NzUzMjc5ODIxNDIwNA.G2"+"vfUr.qJjWqpuFj0qHoiTUb5-V1PAj7GQpnh9UUnR0_U"
}
test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

mainClassName = 'org.jointheleague.Launcher'
